baseURL = 'https://basnetdarpan.com/'
locale = 'en-US'
title = 'Darpan Basnet'
theme = 'vibe-theme'
summaryLength = 30

[params]
  author = "Darpan Basnet"
  description = "Security Analyst, Researcher, and CTF enthusiast. Welcome to my digital garden."
  github = "https://github.com/basnetdarpan"
  linkedin = "https://www.linkedin.com/in/basnetdarpan/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Experiences"
    url = "/experiences/"
    weight = 30

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 40

  [[menu.main]]
    name = "Blogs"
    url = "/posts/"
    weight = 50

[markup]
  [markup.goldmark.renderer]
    unsafe = false
